export default {
  login: "Loreen-netizen",
  id: 56735918,
  node_id: "MDQ6VXNlcjU2NzM1OTE4",
  avatar_url: "https://avatars.githubusercontent.com/u/56735918?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Loreen-netizen",
  html_url: "https://github.com/Loreen-netizen",
  followers_url: "https://api.github.com/users/Loreen-netizen/followers",
  following_url:
    "https://api.github.com/users/Loreen-netizen/following{/other_user}",
  gists_url: "https://api.github.com/users/Loreen-netizen/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Loreen-netizen/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/Loreen-netizen/subscriptions",
  organizations_url: "https://api.github.com/users/Loreen-netizen/orgs",
  repos_url: "https://api.github.com/users/Loreen-netizen/repos",
  events_url: "https://api.github.com/users/Loreen-netizen/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Loreen-netizen/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Creator of Coding Carter",
  twitter_username: "yeukai-loreen",
  public_repos: 30,
  public_gists: 0,
  followers: 14,
  following: 5,
  created_at: "2018-05-06T06:48:23Z",
  updated_at: "2020-05-08T05:01:32Z",
};
